const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const STORAGE='laysflix.state.v3',LIBRARY_V2='laysflix.library.v2',KEY='laysflix.tmdb.key',CACHE_PREFIX='laysflix.cache.';
const STATUS={watchlist:'Quero assistir',watching:'Assistindo',current:'Em dia',paused:'Pausada',watched:'Concluída',abandoned:'Abandonada',rewatching:'Reassistindo'};
const main=$('#main');
let view='home',activeFilter='all',homeData={trending:[],movies:[],series:[],recommendations:[]},activeDetail=null,calendarItems=[],heroTimer=null,heroIndex=0,activeUserId=null,initialHistoryData=null;
const blankState=(profileKind='standard')=>({schema:3,library:[],lists:[],diary:{},watchEvents:[],trash:[],dismissed:[],preferences:{region:'BR',profileKind},historySummary:null,lastBackup:null});
function migrateState(){
  try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved?.schema===3)return {...blankState(),...saved,library:Array.isArray(saved.library)?saved.library:[]}}
  catch{}
  const state=blankState();
  try{state.library=JSON.parse(localStorage.getItem(LIBRARY_V2)||'[]')}catch{}
  try{state.historySummary=JSON.parse(localStorage.getItem('laysflix.history.summary')||'null')}catch{}
  localStorage.setItem(STORAGE,JSON.stringify(state));return state;
}
let state=migrateState();
const stateStorageKey=userId=>userId?`${STORAGE}.${userId}`:STORAGE;
function save(){state.trash=state.trash.filter(x=>Date.now()-x.deletedAt<30*864e5);localStorage.setItem(stateStorageKey(activeUserId),JSON.stringify(state));window.LaysFlixCloud?.queue()}
function stateFromInitialHistory(){const seeded=blankState('lays');if(!initialHistoryData)return seeded;seeded.library=JSON.parse(JSON.stringify(initialHistoryData.library||[]));seeded.historySummary=JSON.parse(JSON.stringify(initialHistoryData.summary||null));seeded.preferences={...seeded.preferences,historySeedVersion:initialHistoryData.version||null};return seeded}
function activateCloudUser(userId,{profileKind='standard'}={}){activeUserId=userId;try{const saved=JSON.parse(localStorage.getItem(stateStorageKey(userId))||'null');if(saved?.schema===3){state={...blankState(profileKind),...saved,preferences:{...blankState(profileKind).preferences,...(saved.preferences||{}),profileKind}}}else state=profileKind==='lays'?stateFromInitialHistory():blankState('standard')}catch{state=profileKind==='lays'?stateFromInitialHistory():blankState('standard')}localStorage.setItem(stateStorageKey(userId),JSON.stringify(state));return state}
function applyCloudState(next,userId,profileKind='standard'){activeUserId=userId;state={...blankState(profileKind),...next,schema:3,library:Array.isArray(next?.library)?next.library:[],preferences:{...blankState(profileKind).preferences,...(next?.preferences||{}),profileKind}};repairHouseOfTheDragon();repairClearedProgress();localStorage.setItem(stateStorageKey(userId),JSON.stringify(state));renderView(view,activeFilter)}
function cloudSessionChanged(session){if(!session){activeUserId=null;state=migrateState()}const avatar=$('#settingsButton'),email=session?.user?.email||'';avatar.textContent=email?email.slice(0,1).toUpperCase():'L';avatar.setAttribute('aria-label',email?`Conta ${email}`:'Perfil e ajustes')}
const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const titleOf=item=>item?.title||item?.name||item?.original_title||item?.original_name||'Sem título';
const typeOf=item=>item?.media_type||item?.type||(item?.first_air_date||item?.name?'tv':'movie');
const uid=item=>`${typeOf(item)}:${item?.id}`;
const yearOf=item=>String(item?.release_date||item?.first_air_date||'—').slice(0,4)||'—';
const image=(path,size='w500')=>path?`https://image.tmdb.org/t/p/${size}${path}`:'';
const poster=item=>image(item?.poster_path,'w500');
const backdrop=(item,size='w1280')=>image(item?.backdrop_path||item?.poster_path,size);
const format=n=>new Intl.NumberFormat('pt-BR').format(Math.round(Number(n)||0));
const today=()=>new Date().toISOString().slice(0,10);
const stored=item=>state.library.find(entry=>uid(entry)===uid(item));
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200);navigator.vibrate?.(18)}
function tmdbAccess(){return localStorage.getItem(KEY)||window.LAYSFLIX_TMDB_TOKEN||window.LAYSFLIX_TMDB_API_KEY||''}
async function tmdb(path){const key=tmdbAccess();if(!key)throw new Error('Configure o acesso ao TMDB no perfil.');const bearer=key.startsWith('eyJ'),join=path.includes('?')?'&':'?';const response=await fetch(`https://api.themoviedb.org/3${path}${bearer?'':`${join}api_key=${encodeURIComponent(key)}`}`,{headers:{accept:'application/json',...(bearer?{Authorization:`Bearer ${key}`}:{})}});if(!response.ok)throw new Error(response.status===401?'Acesso ao TMDB inválido.':'Não foi possível carregar o catálogo.');return response.json()}
async function cached(key,ttl,loader){try{const hit=JSON.parse(localStorage.getItem(CACHE_PREFIX+key)||'null');if(hit&&Date.now()-hit.time<ttl)return hit.data}catch{}const data=await loader();try{localStorage.setItem(CACHE_PREFIX+key,JSON.stringify({time:Date.now(),data}))}catch{}return data}
async function loadInitialHistory(){try{const response=await fetch(`initial-library.json?build=${encodeURIComponent(window.LAYSFLIX_BUILD_ID||'latest')}`,{cache:'no-store'});if(!response.ok)return;const data=await response.json();if(data?.version&&Array.isArray(data.library))initialHistoryData=data}catch(error){console.warn('Histórico inicial indisponível',error)}}
function upsert(item,change={},eventType){const index=state.library.findIndex(entry=>uid(entry)===uid(item)),next={...(index>=0?state.library[index]:item),...item,media_type:typeOf(item),...change,updatedAt:Date.now()};if(index<0)state.library.unshift(next);else state.library[index]=next;state.dismissed=(state.dismissed||[]).filter(id=>id!==uid(next));if(eventType)state.watchEvents.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,type:eventType,item:uid(next),at:new Date().toISOString(),minutes:change.runtime||next.runtime||0});save();toast('Biblioteca atualizada');return next}
function removeFromLibrary(item){const index=state.library.findIndex(entry=>uid(entry)===uid(item));if(index<0)return;const id=uid(state.library[index]);state.trash.unshift({item:state.library[index],deletedAt:Date.now()});state.dismissed=[...new Set([...(state.dismissed||[]),id])];state.library.splice(index,1);save();toast('Removido da biblioteca');history.back()}
function watchedCount(item){return Math.max(Number(item?.watchedEpisodeCount)||0,Object.values(item?.episodes||{}).filter(Boolean).length)}
function repairClearedProgress(){let changed=false;state.library=state.library.map(item=>{if(item.status!=null||watchedCount(item)===0)return item;changed=true;return {...item,episodes:{},watchedEpisodeCount:0,watchedMinutes:0,progressClearedAt:item.progressClearedAt||Date.now()}});if(changed)save()}
function repairHouseOfTheDragon(){const index=state.library.findIndex(item=>uid(item)==='tv:94997');if(index<0)return;const item=state.library[index];if(item.historySource==='manual'||(!watchedCount(item)&&!['watching','current','watched','rewatching'].includes(item.status)))return;state.library[index]={...item,status:item.status==='watchlist'?item.status:null,episodes:{},watchedEpisodeCount:0,watchedMinutes:0,historySource:'corrected',progressClearedAt:Date.now(),updatedAt:Date.now()};save()}
function progress(item){const done=watchedCount(item),total=Number(item?.episodeCount||item?.number_of_episodes)||0;return {done,total,pct:total?Math.min(100,done/total*100):item?.status==='watched'?100:0}}
function card(item,wide=false){const saved=stored(item)||item,p=progress(saved),subtitle=typeOf(saved)==='tv'&&p.done?`${format(p.done)} episódio${p.done===1?'':'s'} assistido${p.done===1?'':'s'}`:`${typeOf(saved)==='tv'?'Série':'Filme'} · ${yearOf(saved)}`;if(wide)return `<article class="wide-card" data-open="${uid(item)}"><img src="${backdrop(item,'w780')}" alt="" loading="lazy"><div><h3>${esc(titleOf(item))}</h3><p>${esc(subtitle)}</p></div></article>`;return `<article class="poster-card" data-open="${uid(item)}"><div class="poster-wrap">${poster(item)?`<img src="${poster(item)}" alt="Capa de ${esc(titleOf(item))}" loading="lazy">`:''}${saved.favorite?'<span class="favorite">♥</span>':''}${p.pct?`<span class="progress"><i style="width:${p.pct}%"></i></span>`:''}</div><h3>${esc(titleOf(item))}</h3><p>${esc(subtitle)}</p></article>`}
function rail(title,items,wide=false,empty=''){if(!items?.length)return empty?`<section class="section"><div class="section-head"><h2>${esc(title)}</h2></div><div class="empty compact">${esc(empty)}</div></section>`:'';return `<section class="section"><div class="section-head"><h2>${esc(title)}</h2></div><div class="rail ${wide?'wide-rail':''}">${items.map(item=>card(item,wide)).join('')}</div></section>`}
function bindCards(root=main){$$('[data-open]',root).forEach(element=>element.onclick=event=>{if(!event.target.closest('button'))openDetail(findItem(element.dataset.open))});$$('[data-add]',root).forEach(element=>element.onclick=()=>upsert(findItem(element.dataset.add),{status:'watchlist'}))}
function findItem(id){return [...state.library,...homeData.trending,...homeData.movies,...homeData.series,...homeData.recommendations].find(item=>uid(item)===id)||{id:Number(id.split(':')[1]),media_type:id.split(':')[0]}}
async function loadIntro(){const intro=$('#intro'),box=$('#introBackdrop'),label=$('#introMovie'),bootstrap=box.style.backgroundImage;const hide=()=>intro.classList.add('hidden');$('#skipIntro').onclick=hide;setTimeout(hide,3900);try{const response=await fetch(`intro-feed.json?build=${encodeURIComponent(window.LAYSFLIX_BUILD_ID||'daily')}`,{cache:'no-store'});if(!response.ok)throw 0;const feed=await response.json(),items=feed.items||[];if(items.length){const last=localStorage.getItem('laysflix.intro.last'),pool=items.filter(item=>String(item.id)!==last),chosen=(pool.length?pool:items)[Math.floor(Math.random()*(pool.length||items.length))];localStorage.setItem('laysflix.intro.last',String(chosen.id));label.innerHTML=`<small>Em alta agora</small><b>${esc(titleOf(chosen))}</b>`;const url=image(chosen.backdrop_path,'original');box.style.backgroundImage=`url('${url}')${bootstrap?`,${bootstrap}`:''}`;const preload=new Image();preload.fetchPriority='high';preload.src=url;(feed.items||[]).filter(item=>item.id!==chosen.id).slice(0,5).forEach(item=>{const warm=new Image();warm.src=image(item.backdrop_path,'w780')})}}catch{}}
async function loadHome(){try{const [trending,movies,series]=await Promise.all([cached('trending',3*3600e3,()=>tmdb('/trending/all/week?language=pt-BR')),cached('movies',6*3600e3,()=>tmdb('/movie/now_playing?language=pt-BR&region=BR')),cached('series',6*3600e3,()=>tmdb('/tv/popular?language=pt-BR'))]);homeData.trending=(trending.results||[]).filter(item=>typeOf(item)!=='person');homeData.movies=movies.results||[];homeData.series=series.results||[];const anchor=state.library.find(item=>item.favorite)||state.library.find(item=>item.status==='watched');if(anchor)try{const rec=await cached(`rec-${uid(anchor)}`,12*3600e3,()=>tmdb(`/${typeOf(anchor)}/${anchor.id}/recommendations?language=pt-BR`));homeData.recommendations=(rec.results||[]).filter(item=>!stored({...item,media_type:typeOf(anchor)})).map(item=>({...item,media_type:typeOf(anchor),reason:`Porque você acompanhou ${titleOf(anchor)}`}))}catch{}if(view==='home')renderHome();if(view==='discover')renderDiscover()}catch(error){toast(error.message)}}
function highlightItems(){const movies=homeData.movies.slice(0,4).map(item=>({...item,media_type:'movie'})),series=[...homeData.trending.filter(item=>typeOf(item)==='tv'),...homeData.series].slice(0,4).map(item=>({...item,media_type:'tv'})),mixed=[];for(let index=0;index<4;index++){if(movies[index])mixed.push(movies[index]);if(series[index])mixed.push(series[index])}const seen=new Set;return mixed.filter(item=>item.backdrop_path&&!seen.has(uid(item))&&seen.add(uid(item))).slice(0,7)}
function activateHero(index){const slides=$$('.hero-slide',main),dots=$$('.hero-dot',main);if(!slides.length)return;heroIndex=(index+slides.length)%slides.length;slides.forEach((slide,position)=>{const active=position===heroIndex;slide.classList.toggle('active',active);slide.setAttribute('aria-hidden',String(!active))});dots.forEach((dot,position)=>dot.classList.toggle('active',position===heroIndex))}
function startHeroCarousel(){clearInterval(heroTimer);const slides=$$('.hero-slide',main);if(slides.length<2)return;$$('.hero-dot',main).forEach((dot,index)=>dot.onclick=()=>{activateHero(index);clearInterval(heroTimer);heroTimer=setInterval(()=>document.hidden||activateHero(heroIndex+1),6000)});heroTimer=setInterval(()=>document.hidden||activateHero(heroIndex+1),6000)}
function renderHome(){const highlights=highlightItems(),fallback=homeData.trending[0]||state.library[0],items=highlights.length?highlights:fallback?[fallback]:[];main.innerHTML=`${items.length?`<section class="home-hero hero-carousel">${items.map((item,index)=>`<article class="hero-slide ${index===0?'active':''}" aria-hidden="${index!==0}"><div class="hero-image" style="background-image:url('${backdrop(item)}')"></div><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow">${typeOf(item)==='tv'?'Série em destaque':'Lançamento em destaque'}</span><h1>${esc(titleOf(item))}</h1><p>${esc(item.overview||'Uma das histórias mais populares para assistir agora.')}</p><div class="hero-actions"><button class="primary" data-open="${uid(item)}">▶ Ver detalhes</button><button class="secondary" data-add="${uid(item)}">＋ Minha lista</button></div></div></article>`).join('')}<div class="hero-dots">${items.map((_,index)=>`<button class="hero-dot ${index===0?'active':''}" aria-label="Destaque ${index+1}"></button>`).join('')}</div></section>`:`<section class="page-title"><p>Bem-vinda ao</p><h1>LaysFlix</h1></section>`}<div class="content">${rail('Continuar assistindo',state.library.filter(item=>['watching','rewatching'].includes(item.status)))}${rail('Para você',homeData.recommendations,true)}${rail('Em alta esta semana',homeData.trending.slice(0,12),true)}${rail('Filmes no cinema',homeData.movies)}${rail('Séries populares',homeData.series)}</div>`;bindCards();startHeroCarousel()}
function nextToWatch(){const show=state.library.find(item=>typeOf(item)==='tv'&&['watching','rewatching'].includes(item.status));if(!show)return null;const done=watchedCount(show)+1;return {...show,nextLabel:`Próximo episódio · ${done} na sua jornada`}}
function renderDiscover(){main.innerHTML=`<section class="page-title"><p>Explore o catálogo</p><h1>Descobrir</h1><form class="discover-search" id="discoverForm"><input type="search" placeholder="O que você quer assistir?"><button>Buscar</button></form></section><div class="content"><div class="chips"><button class="chip active">Para você</button><button class="chip">Filmes</button><button class="chip">Séries</button><button class="chip">Em alta</button></div>${rail('Recomendações personalizadas',homeData.recommendations,true,'Avalie ou favorite títulos para receber recomendações.')}${rail('Tendências',homeData.trending,true)}${rail('Filmes para hoje',homeData.movies)}${rail('Séries para maratonar',homeData.series)}</div>`;$('#discoverForm').onsubmit=event=>{event.preventDefault();openSearch($('input',event.currentTarget).value)};bindCards()}
function renderLibrary(filter=activeFilter){activeFilter=filter;const matches=item=>filter==='all'||filter==='favorite'&&item.favorite||filter==='episodes'&&watchedCount(item)>0||item.status===filter||filter.startsWith('list:')&&(state.lists.find(list=>list.id===filter.slice(5))?.items||[]).includes(uid(item));const items=state.library.filter(matches);main.innerHTML=`<section class="page-title"><p>${state.library.length} títulos salvos</p><h1>Biblioteca</h1></section><div class="content"><div class="chips" id="libraryFilters">${[['all','Tudo'],['watching','Assistindo'],['episodes','Com progresso'],['watchlist','Quero ver'],['watched','Concluídos'],['paused','Pausadas'],['abandoned','Abandonadas'],['favorite','Favoritos']].map(([key,label])=>`<button class="chip ${filter===key?'active':''}" data-filter="${key}">${label}</button>`).join('')}${state.lists.map(list=>`<button class="chip ${filter===`list:${list.id}`?'active':''}" data-filter="list:${list.id}">${esc(list.name)}</button>`).join('')}</div>${items.length?`<div class="grid">${items.map(item=>card(item)).join('')}</div>`:'<div class="empty"><b>Nada por aqui ainda</b>Escolha outro filtro ou adicione um título.</div>'}</div>`;$('#libraryFilters').onclick=event=>{if(event.target.dataset.filter)renderLibrary(event.target.dataset.filter)};bindCards()}
function historyTotals(){const summary=state.historySummary||{},series=state.library.filter(item=>typeOf(item)==='tv'&&watchedCount(item)>0).length,movies=state.library.filter(item=>typeOf(item)==='movie'&&item.status==='watched').length,episodes=state.library.filter(item=>typeOf(item)==='tv').reduce((total,item)=>total+watchedCount(item),0),seriesMinutes=summary.seriesSeconds?summary.seriesSeconds/60:state.library.filter(item=>typeOf(item)==='tv').reduce((total,item)=>total+(item.watchedMinutes||0),0),movieMinutes=summary.movieSeconds?summary.movieSeconds/60:state.library.filter(item=>typeOf(item)==='movie').reduce((total,item)=>total+(item.watchedMinutes||0),0);return {series:Math.max(summary.seriesWatched||0,series),movies:Math.max(summary.moviesWatched||0,movies),episodes:Math.max(summary.episodesWatched||0,episodes),seriesMinutes,movieMinutes,hours:Math.round((seriesMinutes+movieMinutes)/60)}}
function monthlyStats(){const months=Array.from({length:6},(_,index)=>{const date=new Date();date.setMonth(date.getMonth()-5+index);return {key:date.toISOString().slice(0,7),label:date.toLocaleDateString('pt-BR',{month:'short'}),count:0}});state.watchEvents.forEach(event=>{const month=months.find(item=>item.key===event.at.slice(0,7));if(month)month.count++});const max=Math.max(...months.map(item=>item.count),1);return `<div class="mini-chart">${months.map(item=>`<div><i style="height:${Math.max(8,item.count/max*100)}%"></i><b>${item.count}</b><small>${item.label.replace('.','')}</small></div>`).join('')}</div>`}
function heatmap(){const days=Array.from({length:35},(_,offset)=>{const date=new Date();date.setDate(date.getDate()-34+offset);const key=date.toISOString().slice(0,10),count=state.watchEvents.filter(event=>event.at.startsWith(key)).length;return `<i class="heat-${Math.min(4,count)}" title="${key}: ${count}"></i>`});return `<div class="heatmap">${days.join('')}</div>`}
function topGenres(){const counts={};state.library.forEach(item=>(item.genres||[]).forEach(genre=>counts[genre.name]=(counts[genre.name]||0)+1));return Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5)}
function renderProfile(){const total=historyTotals(),favorites=state.library.filter(item=>item.favorite).length,genres=topGenres(),maxGenre=Math.max(...genres.map(([,value])=>value),1);main.innerHTML=`<section class="page-title"><p>Sua história em números</p><h1>Dashboard</h1></section><div class="content"><section class="dashboard-hero"><small>Tempo total assistido</small><strong>${format(total.hours)}h</strong><p>aproximadamente ${format(total.hours/24)} dias de histórias</p></section><div class="dashboard-grid"><article class="metric-card"><span>▣</span><strong>${format(total.episodes)}</strong><small>episódios assistidos</small></article><article class="metric-card"><span>◫</span><strong>${format(total.series)}</strong><small>séries acompanhadas</small></article><article class="metric-card"><span>▶</span><strong>${format(total.movies)}</strong><small>filmes assistidos</small></article><article class="metric-card"><span>♥</span><strong>${format(favorites)}</strong><small>favoritos</small></article></div><section class="stats-card"><div class="section-head"><h2>Últimos 6 meses</h2></div>${monthlyStats()}</section><section class="stats-card"><div class="section-head"><h2>Constância</h2></div>${heatmap()}<p class="hint">Cada quadrado representa um dia de atividade no LaysFlix.</p></section>${genres.length?`<section class="stats-card"><div class="section-head"><h2>Gêneros da biblioteca</h2></div><div class="genre-stats">${genres.map(([name,value])=>`<div><span>${esc(name)}</span><i><b style="width:${value/maxGenre*100}%"></b></i><strong>${value}</strong></div>`).join('')}</div></section>`:''}<section class="section"><div class="section-head"><h2>Sua jornada</h2></div><div class="profile-actions"><button data-go="calendar"><span>▦ Calendário inteligente</span><b>›</b></button><button data-library="watching"><span>▶ Assistindo agora</span><b>${state.library.filter(item=>item.status==='watching').length} ›</b></button><button data-library="paused"><span>Ⅱ Séries pausadas</span><b>${state.library.filter(item=>item.status==='paused').length} ›</b></button><button id="profileSettings"><span>⚙ Ajustes e backup</span><b>›</b></button></div></section>${rail('Continue de onde parou',state.library.filter(item=>item.status==='watching'))}<p class="history-note">Histórico inicial recuperado do backup do TV Time.</p></div>`;$('#profileSettings').onclick=openSettings;$$('[data-library]',main).forEach(button=>button.onclick=()=>navigateView('library',button.dataset.library));$$('[data-go]',main).forEach(button=>button.onclick=()=>navigateView(button.dataset.go)) ;bindCards()}
async function renderCalendar(){main.innerHTML='<section class="page-title"><p>Próximos lançamentos</p><h1>Calendário</h1></section><div class="content"><div class="skeleton calendar-skeleton"></div></div>';const shows=state.library.filter(item=>typeOf(item)==='tv'&&['watching','current','watchlist','rewatching'].includes(item.status)).sort((a,b)=>String(b.first_air_date||'').localeCompare(String(a.first_air_date||''))).slice(0,60);const details=await Promise.all(shows.map(async show=>{try{return {...show,...await cached(`calendar-${show.id}`,6*3600e3,()=>tmdb(`/tv/${show.id}?language=pt-BR`))}}catch{return show}}));calendarItems=details.filter(item=>item.next_episode_to_air?.air_date).sort((a,b)=>a.next_episode_to_air.air_date.localeCompare(b.next_episode_to_air.air_date));const available=details.filter(item=>item.last_episode_to_air&&watchedCount(item)<Number(item.number_of_episodes||0)).sort((a,b)=>String(b.last_episode_to_air?.air_date||'').localeCompare(String(a.last_episode_to_air?.air_date||''))).slice(0,12);main.innerHTML=`<section class="page-title calendar-title"><p>Sua agenda de histórias</p><h1>Calendário</h1><span>${shows.length} séries monitoradas</span></section><div class="content"><button class="secondary calendar-back" data-go="profile">‹ Voltar ao Dashboard</button>${calendarItems.length?`<div class="calendar-list">${calendarItems.map(item=>{const episode=item.next_episode_to_air,date=new Date(`${episode.air_date}T12:00:00`);return `<article data-open="${uid(item)}"><time><b>${date.getDate()}</b><small>${date.toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></time><div><span>${esc(titleOf(item))}</span><h3>T${episode.season_number}:E${episode.episode_number} · ${esc(episode.name||'Novo episódio')}</h3><p>${date>=new Date()?'Próxima estreia':'Já disponível'} · ${date.toLocaleDateString('pt-BR',{weekday:'long'})}</p></div></article>`}).join('')}</div>`:'<div class="empty calendar-empty"><b>Nenhuma data futura confirmada</b>As séries acompanhadas foram verificadas, mas o TMDB ainda não publicou novos episódios com data.</div>'}${rail('Episódios recentes para colocar em dia',available)}</div>`;$$('[data-go]',main).forEach(button=>button.onclick=()=>navigateView(button.dataset.go));bindCards()}
function applyPalette(item){const palettes=[['#f62670','#ff7958'],['#7c4dff','#36c5f0'],['#e24747','#f5a642'],['#2582ff','#58dbc5'],['#d291ff','#ff6ca8']],[a,b]=palettes[Number(item?.id||0)%palettes.length];document.documentElement.style.setProperty('--accent',a);document.documentElement.style.setProperty('--accent2',b)}
async function openDetail(seed,push=true){if(!seed)return;closeSearch();if(push)history.pushState({kind:'detail',item:seed,base:view},'',`#${typeOf(seed)}/${seed.id}`);activeDetail=seed;applyPalette(seed);const layer=$('#detailPage');layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#detailContent').innerHTML='<div class="detail-backdrop skeleton"></div><div class="detail-body"><div class="skeleton detail-skeleton"></div></div>';try{const type=typeOf(seed),[detail,credits,videos,providers,recommendations]=await Promise.all([cached(`detail-${uid(seed)}`,6*3600e3,()=>tmdb(`/${type}/${seed.id}?language=pt-BR`)),cached(`credits-${uid(seed)}`,24*3600e3,()=>tmdb(`/${type}/${seed.id}/credits?language=pt-BR`)),cached(`videos-${uid(seed)}`,24*3600e3,()=>tmdb(`/${type}/${seed.id}/videos?language=pt-BR`)),cached(`providers-${uid(seed)}`,6*3600e3,()=>tmdb(`/${type}/${seed.id}/watch/providers`)),cached(`similar-${uid(seed)}`,24*3600e3,()=>tmdb(`/${type}/${seed.id}/recommendations?language=pt-BR`))]);const item={...seed,...detail,media_type:type};activeDetail=item;renderDetail(item,stored(item)||item,credits.cast||[],videos.results||[],providers.results?.BR,recommendations.results||[])}catch(error){renderDetail(seed,stored(seed)||seed,[],[],null,[]);toast(error.message)}}
function providerGroup(title,items=[]){return items.length?`<div class="provider-group"><h3>${title}</h3><div>${items.map(provider=>`<span><img src="${image(provider.logo_path,'w92')}" alt=""><small>${esc(provider.provider_name)}</small></span>`).join('')}</div></div>`:''}
function providersBlock(data){if(!data)return '<div class="empty compact"><b>Disponibilidade não encontrada</b>O TMDB ainda não possui provedores para o Brasil.</div>';return `<section class="section providers"><div class="section-head"><h2>Onde assistir</h2><a href="${esc(data.link||'https://www.themoviedb.org')}" target="_blank" rel="noopener">Ver opções</a></div>${providerGroup('Por assinatura',data.flatrate)}${providerGroup('Alugar',data.rent)}${providerGroup('Comprar',data.buy)}<p class="provider-credit">Disponibilidade no Brasil fornecida por JustWatch via TMDB.</p></section>`}
function listControls(item){return `<div class="list-controls"><label>Adicionar a uma lista<select id="detailList"><option value="">Selecione</option>${state.lists.map(list=>`<option value="${list.id}" ${list.items.includes(uid(item))?'selected':''}>${esc(list.name)}</option>`).join('')}</select></label><button id="addDetailList">Adicionar</button></div>`}
function diaryBlock(item){const entry=state.diary[uid(item)]||{};return `<section class="section diary-card"><div class="section-head"><h2>Meu diário</h2><span>Salvo no iPhone</span></div><div class="rating-row"><label>Minha nota<select id="diaryRating"><option value="">—</option>${Array.from({length:11},(_,index)=>`<option value="${index}" ${String(entry.rating)===String(index)?'selected':''}>${index}</option>`).join('')}</select></label><label>Data<input id="diaryDate" type="date" value="${esc(entry.date||today())}"></label></div><textarea id="diaryNote" rows="4" placeholder="Comentários, teorias e lembranças…">${esc(entry.note||'')}</textarea><label class="check-label"><input id="diaryRewatch" type="checkbox" ${entry.rewatch?'checked':''}> Foi uma reassistida</label><button id="saveDiary" class="primary full">Salvar no diário</button></section>`}
function renderDetail(item,saved,cast,videos,providers,recommendations){const runtime=item.runtime||(item.episode_run_time||[])[0],genres=(item.genres||[]).slice(0,3),p=progress(saved),trailer=videos.find(video=>video.site==='YouTube'&&video.type==='Trailer');$('#detailContent').innerHTML=`<div class="detail-backdrop" style="background-image:url('${backdrop(item)}')"><button class="back" data-close-detail>‹</button></div><div class="detail-body"><div class="detail-meta"><span class="pill">${typeOf(item)==='tv'?'Série':'Filme'}</span><span class="pill">${yearOf(item)}</span>${runtime?`<span class="pill">${runtime} min</span>`:''}${item.vote_average?`<span class="pill">★ ${item.vote_average.toFixed(1)}</span>`:''}${p.done?`<span class="pill">✓ ${format(p.done)} assistidos</span>`:''}</div><h1>${esc(titleOf(item))}</h1><p>${genres.map(genre=>esc(genre.name)).join(' · ')}</p>${typeOf(item)==='tv'&&p.total?`<div class="detail-progress"><span><b>${format(p.done)} de ${format(p.total)}</b><small>${format(p.total-p.done)} restantes</small></span><i><b style="width:${p.pct}%"></b></i></div>`:''}<p class="detail-overview">${esc(item.overview||'Sinopse não disponível.')}</p><div class="detail-actions">${Object.entries(STATUS).map(([key,label])=>`<button data-status="${key}" class="${saved.status===key?'active':''}">${saved.status===key?'✓ ':''}${label}</button>`).join('')}<button data-fav class="${saved.favorite?'active':''}">${saved.favorite?'♥ Favorito':'♡ Favoritar'}</button></div>${listControls(item)}${providersBlock(providers)}${cast.length?`<section class="section"><div class="section-head"><h2>Elenco</h2></div><div class="people">${cast.slice(0,14).map(person=>`<div class="person">${person.profile_path?`<img src="${image(person.profile_path,'w185')}" alt="">`:'<div class="person-placeholder"></div>'}<span>${esc(person.name)}</span></div>`).join('')}</div></section>`:''}${typeOf(item)==='tv'&&item.seasons?.length?`<section class="section episode-section"><div class="section-head"><h2>Episódios</h2><button id="nextEpisode">Próximo ›</button></div><div class="season-toolbar"><select class="season-select" id="seasonSelect">${item.seasons.filter(season=>season.season_number>0).map(season=>`<option value="${season.season_number}">${esc(season.name)}</option>`).join('')}</select><button id="toggleSeason">Marcar temporada</button></div><div id="episodes"><div class="skeleton episode-loading"></div></div></section>`:''}${diaryBlock(item)}${trailer?`<a class="primary trailer" target="_blank" rel="noopener" href="https://youtube.com/watch?v=${esc(trailer.key)}">▶ Assistir trailer</a>`:''}${recommendations.length?rail('Você também pode gostar',recommendations.slice(0,12).map(entry=>({...entry,media_type:typeOf(item)}))):''}<button id="removeTitle" class="danger-button">Remover da biblioteca</button></div>`;bindDetail(item,saved,cast,videos,providers,recommendations)}
function bindDetail(item,saved,cast,videos,providers,recommendations){$('[data-close-detail]').onclick=()=>history.back();$$('[data-status]',$('#detailContent')).forEach(button=>button.onclick=()=>{const clearing=saved.status===button.dataset.status,status=clearing?null:button.dataset.status,change=clearing&&button.dataset.status==='watched'?{status,episodes:{},watchedEpisodeCount:0,watchedMinutes:0,historySource:'manual',progressClearedAt:Date.now()}:{status,historySource:'manual',progressClearedAt:null};const next=upsert(item,change,status==='watched'?'title-watched':null);renderDetail(item,next,cast,videos,providers,recommendations)});$('[data-fav]').onclick=()=>{const next=upsert(item,{favorite:!saved.favorite});renderDetail(item,next,cast,videos,providers,recommendations)};$('#addDetailList').onclick=()=>{const id=$('#detailList').value;if(!id)return toast('Escolha uma lista');const list=state.lists.find(entry=>entry.id===id);if(!list.items.includes(uid(item)))list.items.push(uid(item));save();toast(`Adicionado a ${list.name}`)};$('#saveDiary').onclick=()=>{state.diary[uid(item)]={rating:$('#diaryRating').value,note:$('#diaryNote').value.trim(),date:$('#diaryDate').value,rewatch:$('#diaryRewatch').checked,updatedAt:Date.now()};save();toast('Diário salvo')};$('#removeTitle').onclick=()=>removeFromLibrary(item);if($('#seasonSelect')){$('#seasonSelect').onchange=()=>loadEpisodes(item,+$('#seasonSelect').value);$('#toggleSeason').onclick=()=>toggleSeason(item,+$('#seasonSelect').value);$('#nextEpisode').onclick=()=>openNextEpisode(item);loadEpisodes(item,+$('#seasonSelect').value)}bindCards($('#detailContent'))}
async function seasonData(show,season){const pt=await cached(`season-${show.id}-${season}-pt`,12*3600e3,()=>tmdb(`/tv/${show.id}/season/${season}?language=pt-BR`));if((pt.episodes||[]).every(episode=>episode.overview))return pt;try{const en=await cached(`season-${show.id}-${season}-en`,24*3600e3,()=>tmdb(`/tv/${show.id}/season/${season}?language=en-US`)),english=new Map((en.episodes||[]).map(episode=>[episode.episode_number,episode]));return {...pt,episodes:(pt.episodes||[]).map(episode=>({...english.get(episode.episode_number),...episode,overview:episode.overview||english.get(episode.episode_number)?.overview||''}))}}catch{return pt}}
function episodeDiaryKey(show,season,episode){return `${uid(show)}:${season}:${episode}`}
async function loadEpisodes(show,season,focusKey){const box=$('#episodes');box.innerHTML='<div class="skeleton episode-loading"></div>';try{const data=await seasonData(show,season),saved=stored(show)||show,episodes=saved.episodes||{},allDone=data.episodes.length&&data.episodes.every(episode=>episodes[`${season}:${episode.episode_number}`]);$('#toggleSeason').textContent=allDone?'Desmarcar temporada':'Marcar temporada';box.innerHTML=(data.episodes||[]).map(episode=>{const key=`${season}:${episode.episode_number}`,done=!!episodes[key],diary=state.diary[episodeDiaryKey(show,season,episode.episode_number)]||{},still=image(episode.still_path||show.backdrop_path,'w500');return `<article class="episode-card ${done?'done':''}" data-episode-card="${key}"><div class="episode-still">${still?`<img src="${still}" alt="Imagem do episódio ${episode.episode_number}" loading="lazy">`:''}<button class="episode-check ${done?'done':''}" data-episode="${key}" aria-label="${done?'Desmarcar':'Marcar'} episódio como assistido">${done?'✓':''}</button></div><div class="episode-copy"><div class="episode-title"><span>T${season}:E${episode.episode_number}</span>${episode.vote_average?`<small>★ ${episode.vote_average.toFixed(1)}</small>`:''}</div><h3>${esc(episode.name||`Episódio ${episode.episode_number}`)}</h3><p class="episode-meta">${episode.runtime?`${episode.runtime} min · `:''}${episode.air_date?new Date(`${episode.air_date}T12:00:00`).toLocaleDateString('pt-BR'):'Data indisponível'}</p><p class="episode-overview">${esc(episode.overview||'Sinopse ainda não disponível.')}</p><details><summary>Meu diário do episódio</summary><textarea data-episode-note="${key}" rows="2" placeholder="O que achou deste episódio?">${esc(diary.note||'')}</textarea></details></div></article>`}).join('');$$('[data-episode]',box).forEach(button=>button.onclick=()=>toggleEpisode(show,button.dataset.episode));$$('[data-episode-note]',box).forEach(textarea=>textarea.onchange=()=>{const [s,e]=textarea.dataset.episodeNote.split(':');state.diary[episodeDiaryKey(show,s,e)]={...(state.diary[episodeDiaryKey(show,s,e)]||{}),note:textarea.value.trim(),date:today(),updatedAt:Date.now()};save();toast('Nota do episódio salva')});if(focusKey)$(`[data-episode-card="${focusKey}"]`,box)?.scrollIntoView({behavior:'smooth',block:'center'})}catch(error){box.innerHTML=`<div class="empty compact"><b>Não foi possível carregar</b>${esc(error.message)}</div>`}}
function toggleEpisode(show,key){const current=stored(show)||show,episodes={...(current.episodes||{})},wasDone=!!episodes[key];episodes[key]=!wasDone;const count=Object.values(episodes).filter(Boolean).length,total=activeDetail?.number_of_episodes||current.episodeCount||0,status=count===0?null:total&&count>=total?'current':current.status==='rewatching'?'rewatching':'watching';upsert(activeDetail||show,{episodes,watchedEpisodeCount:count,episodeCount:total,status,historySource:'manual',progressClearedAt:count?null:Date.now()},wasDone?'episode-unwatched':'episode-watched');loadEpisodes(activeDetail||show,+$('#seasonSelect').value,key)}
async function toggleSeason(show,season){try{const data=await seasonData(show,season),current=stored(show)||show,episodes={...(current.episodes||{})},keys=data.episodes.map(episode=>`${season}:${episode.episode_number}`),allDone=keys.every(key=>episodes[key]);keys.forEach(key=>episodes[key]=!allDone);const count=Object.values(episodes).filter(Boolean).length,total=activeDetail?.number_of_episodes||current.episodeCount||count,status=count===0?null:count>=total?'current':'watching';upsert(activeDetail||show,{episodes,watchedEpisodeCount:count,episodeCount:total,status,historySource:'manual',progressClearedAt:count?null:Date.now()},allDone?'season-unwatched':'season-watched');await loadEpisodes(activeDetail||show,season);toast(allDone?'Temporada desmarcada':'Temporada concluída')}catch(error){toast(error.message)}}
async function openNextEpisode(show){const current=stored(show)||show,seasons=(activeDetail?.seasons||[]).filter(season=>season.season_number>0);for(const season of seasons){const data=await seasonData(show,season.season_number),episode=(data.episodes||[]).find(entry=>!current.episodes?.[`${season.season_number}:${entry.episode_number}`]);if(episode){$('#seasonSelect').value=String(season.season_number);await loadEpisodes(show,season.season_number,`${season.season_number}:${episode.episode_number}`);return}}toast('Todos os episódios disponíveis foram assistidos')}
function enhanceDashboard(){const content=$('.content',main),hero=$('.dashboard-hero',main),grid=$('.dashboard-grid',main);if(!content||!hero||!grid)return;const totals=historyTotals(),watching=state.library.filter(item=>typeOf(item)==='tv'&&['watching','current','rewatching'].includes(item.status)),featured=watching.find(item=>item.backdrop_path)||state.library.find(item=>item.backdrop_path);hero.style.setProperty('--dashboard-art',`url('${backdrop(featured)}')`);const calendar=document.createElement('button');calendar.className='calendar-spotlight';calendar.innerHTML=`<span class="calendar-icon"><b>${new Date().getDate()}</b><small>${new Date().toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</small></span><span><small>AGENDA INTELIGENTE</small><strong>Calendário de lançamentos</strong><em>${watching.length} séries sendo monitoradas</em></span><i>›</i>`;calendar.onclick=()=>navigateView('calendar');hero.after(calendar);const formatCard=document.createElement('section');const seriesHours=Math.round(totals.seriesMinutes/60),movieHours=Math.round(totals.movieMinutes/60),seriesPct=Math.round(totals.seriesMinutes/(totals.seriesMinutes+totals.movieMinutes||1)*100);formatCard.className='format-premium';formatCard.innerHTML=`<div class="format-ring" style="--series:${seriesPct*3.6}deg"><span><b>${seriesPct}%</b><small>séries</small></span></div><div><small>COMO VOCÊ ASSISTE</small><h2>${format(seriesHours)}h em séries</h2><p>e ${format(movieHours)}h em filmes</p><div class="format-legend"><span><i></i>Séries</span><span><i></i>Filmes</span></div></div>`;grid.after(formatCard);if(!state.watchEvents.length){const chart=$('.mini-chart',main),heat=$('.heatmap',main);if(chart){const section=chart.closest('.stats-card');$('h2',section).textContent='Uma vida de histórias';chart.outerHTML=`<div class="legacy-story"><span><b>${format(totals.hours)}</b><small>horas</small></span><i></i><span><b>${format(totals.episodes)}</b><small>episódios</small></span><i></i><span><b>${format(totals.movies+totals.series)}</b><small>produções</small></span></div><p class="legacy-copy">Seu histórico anterior foi recuperado. Os gráficos mensais começam a ganhar vida com as próximas marcações.</p>`}heat?.closest('.stats-card')?.remove()}}
function renderView(next,filter){view=next;if(next!=='home')clearInterval(heroTimer);$$('.tabbar button').forEach(button=>button.classList.toggle('active',button.dataset.view===next));scrollTo(0,0);const renderer={home:renderHome,discover:renderDiscover,library:()=>renderLibrary(filter),profile:renderProfile,calendar:renderCalendar}[next]||renderHome;renderer();if(next==='profile')enhanceDashboard()}
function navigateView(next,filter,replace=false){history[replace?'replaceState':'pushState']({kind:'view',view:next,filter},'',`#${next}`);renderView(next,filter)}
function closeDetail(){const layer=$('#detailPage');layer.classList.remove('open');layer.setAttribute('aria-hidden','true');document.body.style.overflow='';activeDetail=null}
function closeSearch(){const layer=$('#searchPage');layer.classList.remove('open');layer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openSearch(initial='',push=true){closeDetail();if(push)history.pushState({kind:'search',query:initial,base:view},'','#search');const layer=$('#searchPage');layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#searchInput').value=initial;$('#searchInput').focus();if(initial)search(initial)}
async function search(query){const box=$('#searchResults');box.innerHTML='<div class="skeleton search-loading"></div>';try{const data=await tmdb(`/search/multi?language=pt-BR&include_adult=false&query=${encodeURIComponent(query)}`),items=(data.results||[]).filter(item=>['movie','tv'].includes(typeOf(item)));box.innerHTML=items.length?items.map(item=>`<article class="search-row" data-search-open="${uid(item)}">${poster(item)?`<img src="${poster(item)}" alt="">`:'<div class="search-placeholder"></div>'}<div><small>${typeOf(item)==='tv'?'Série':'Filme'} · ${yearOf(item)}</small><h3>${esc(titleOf(item))}</h3><p>${esc(item.overview||'Sem sinopse.')}</p></div></article>`).join(''):'<div class="empty"><b>Nenhum resultado</b>Tente outro título.</div>';$$('[data-search-open]',box).forEach(row=>row.onclick=()=>openDetail(items.find(item=>uid(item)===row.dataset.searchOpen)))}catch(error){box.innerHTML=`<div class="empty"><b>Busca indisponível</b>${esc(error.message)}</div>`}}
function applyHistory(next){closeDetail();closeSearch();if(next?.kind==='detail'){renderView(next.base||'home');openDetail(next.item,false)}else if(next?.kind==='search'){renderView(next.base||'home');openSearch(next.query||'',false)}else renderView(next?.view||'home',next?.filter)}
function renderCustomLists(){const box=$('#customLists');box.innerHTML=state.lists.length?state.lists.map(list=>`<div class="settings-list"><span><i style="background:${esc(list.color||'#f62670')}"></i>${esc(list.name)} <small>${list.items.length}</small></span><button data-delete-list="${list.id}">×</button></div>`).join(''):'<p class="hint">Crie listas como Doramas, Terror ou Séries de conforto.</p>';$$('[data-delete-list]',box).forEach(button=>button.onclick=()=>{state.lists=state.lists.filter(list=>list.id!==button.dataset.deleteList);save();renderCustomLists();toast('Lista removida')})}
function openSettings(){$('#tmdbKey').value=localStorage.getItem(KEY)||'';$('#backupStatus').textContent=state.lastBackup?`Último backup: ${new Date(state.lastBackup).toLocaleString('pt-BR')}`:'Você ainda não exportou um backup completo.';$('#restoreTrash').textContent=`Lixeira (${state.trash.length})`;renderCustomLists();$('#settings').showModal()}
function exportBackup(){state.lastBackup=new Date().toISOString();save();const blob=new Blob([JSON.stringify({app:'LaysFlix',schema:3,exportedAt:state.lastBackup,state},null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`laysflix-backup-${today()}.json`;link.click();URL.revokeObjectURL(link.href);toast('Backup completo exportado')}
async function importBackup(file){try{const data=JSON.parse(await file.text()),incoming=data.state||data;if(!Array.isArray(incoming.library))throw 0;if(!confirm(`Importar ${incoming.library.length} títulos? O backup atual será substituído, mas você poderá exportá-lo antes.`))return;state={...blankState(),...incoming,schema:3,library:incoming.library};save();$('#settings').close();navigateView('library');toast('Backup importado com sucesso')}catch{toast('Backup inválido ou incompatível')}}
function restoreTrash(){if(!state.trash.length)return toast('A lixeira está vazia');const items=state.trash.map(entry=>entry.item),existing=new Set(state.library.map(uid)),restored=items.filter(item=>!existing.has(uid(item)));state.library.push(...restored);const ids=new Set(restored.map(uid));state.dismissed=(state.dismissed||[]).filter(id=>!ids.has(id));state.trash=[];save();renderCustomLists();$('#restoreTrash').textContent='Lixeira (0)';toast(`${items.length} título${items.length===1?' restaurado':'s restaurados'}`)}
function clearCache(){Object.keys(localStorage).filter(key=>key.startsWith(CACHE_PREFIX)).forEach(key=>localStorage.removeItem(key));homeData={trending:[],movies:[],series:[],recommendations:[]};toast('Cache atualizado');loadHome()}
$$('.tabbar button').forEach(button=>button.onclick=()=>navigateView(button.dataset.view));$('#brandButton').onclick=()=>navigateView('home');$('#searchButton').onclick=()=>openSearch();$('#settingsButton').onclick=openSettings;$('#settings .close').onclick=()=>$('#settings').close();$('#saveKey').onclick=()=>{const value=$('#tmdbKey').value.trim();value?localStorage.setItem(KEY,value):localStorage.removeItem(KEY);$('#settings').close();clearCache()};$('#createList').onclick=()=>{const input=$('#newListName'),name=input.value.trim();if(!name)return toast('Digite o nome da lista');state.lists.push({id:crypto.randomUUID?.()||String(Date.now()),name,color:['#f62670','#7c4dff','#2582ff','#f5a642'][state.lists.length%4],items:[]});input.value='';save();renderCustomLists();toast('Lista criada')};$('#exportData').onclick=exportBackup;$('#importData').onchange=event=>event.target.files[0]&&importBackup(event.target.files[0]);$('#restoreTrash').onclick=restoreTrash;$('#clearCache').onclick=clearCache;$('#searchForm').onsubmit=event=>{event.preventDefault();const query=$('#searchInput').value.trim();if(query){history.replaceState({...history.state,query},'','#search');search(query)}};$('[data-close-search]').onclick=()=>history.back();addEventListener('popstate',event=>applyHistory(event.state));
let swipeGesture=null;
function blocksNavigationSwipe(target){return target instanceof Element&&Boolean(target.closest('input,textarea,select,[contenteditable],dialog,.rail,.chips,.people,.hero-dots'))}
addEventListener('touchstart',event=>{if(event.touches.length!==1||blocksNavigationSwipe(event.target))return swipeGesture=null;const touch=event.touches[0];swipeGesture={x:touch.clientX,y:touch.clientY,at:Date.now(),horizontal:false}},{passive:true});
addEventListener('touchmove',event=>{if(!swipeGesture||event.touches.length!==1)return;const touch=event.touches[0],dx=touch.clientX-swipeGesture.x,dy=touch.clientY-swipeGesture.y;if(!swipeGesture.horizontal&&Math.abs(dy)>18&&Math.abs(dy)>Math.abs(dx))return swipeGesture=null;if(Math.abs(dx)>14&&Math.abs(dx)>Math.abs(dy)*1.15){swipeGesture.horizontal=true;event.preventDefault()}},{passive:false});
addEventListener('touchend',event=>{if(!swipeGesture)return;const touch=event.changedTouches[0],dx=touch.clientX-swipeGesture.x,dy=touch.clientY-swipeGesture.y,elapsed=Date.now()-swipeGesture.at,valid=swipeGesture.horizontal&&Math.abs(dx)>=72&&Math.abs(dx)>Math.abs(dy)*1.35&&elapsed<1100;swipeGesture=null;if(!valid)return;dx>0?history.back():history.forward()},{passive:true});
addEventListener('touchcancel',()=>swipeGesture=null,{passive:true});
async function boot(){loadIntro();await loadInitialHistory();repairHouseOfTheDragon();repairClearedProgress();history.replaceState({kind:'view',view:'home'},'','#home');renderHome();loadHome();save();await window.LaysFlixCloud?.init({getState:()=>state,activateUser:activateCloudUser,applyState:applyCloudState,onSession:cloudSessionChanged,onCloudStatus:()=>{}})}
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=21'));
boot();
