const STORE='laysflix.library.v1',KEY='laysflix.tmdb.key';
const $=selector=>document.querySelector(selector),grid=$('#grid'),message=$('#message');
let library=JSON.parse(localStorage.getItem(STORE)||'[]'),results=[],mode='library';
const save=()=>{localStorage.setItem(STORE,JSON.stringify(library));renderStats()};
const titleOf=item=>item.title||item.name||'Sem título';
const typeOf=item=>item.media_type||(item.first_air_date?'tv':'movie');
const uid=item=>`${typeOf(item)}:${item.id}`;
const poster=item=>item.poster_path?`https://image.tmdb.org/t/p/w500${item.poster_path}`:'';
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function renderStats(){ $('#totalCount').textContent=library.length;$('#watchingCount').textContent=library.filter(x=>x.status==='watching').length;$('#watchedCount').textContent=library.filter(x=>x.status==='watched').length }
function render(){const filter=$('#filter').value;const items=mode==='search'?results:library.filter(x=>filter==='all'||(filter==='favorite'?x.favorite:x.status===filter));$('#sectionTitle').textContent=mode==='search'?'Resultados':'Minha biblioteca';grid.innerHTML='';message.textContent=items.length?'':mode==='search'?'Nenhum resultado encontrado.':'Sua biblioteca está vazia. Busque um título para começar.';items.forEach(item=>{const card=document.createElement('article');card.className='card';const status={watching:'Assistindo',watchlist:'Quero ver',watched:'Assistido'}[item.status];card.innerHTML=`${poster(item)?`<img src="${poster(item)}" alt="Capa de ${escapeHtml(titleOf(item))}" loading="lazy">`:`<div class="poster-placeholder">Sem capa</div>`}${status?`<span class="badge">${status}</span>`:''}<div class="card-info"><h3>${escapeHtml(titleOf(item))}</h3><p>${typeOf(item)==='tv'?'Série':'Filme'} · ${(item.release_date||item.first_air_date||'').slice(0,4)||'—'}</p></div>`;card.onclick=()=>openDetails(item);grid.append(card)})}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function tmdb(path){const key=localStorage.getItem(KEY);if(!key)throw new Error('Configure sua chave do TMDB nos ajustes.');const auth=key.startsWith('eyJ')?{Authorization:`Bearer ${key}`}:{ };const join=path.includes('?')?'&':'?';const apiKey=key.startsWith('eyJ')?'':`${join}api_key=${encodeURIComponent(key)}`;const response=await fetch(`https://api.themoviedb.org/3${path}${apiKey}`,{headers:{...auth,accept:'application/json'}});if(!response.ok)throw new Error(response.status===401?'Chave do TMDB inválida.':'Não foi possível consultar o TMDB.');return response.json()}
$('#searchForm').onsubmit=async event=>{event.preventDefault();const query=$('#searchInput').value.trim();if(!query)return;message.textContent='Buscando…';grid.innerHTML='';try{const data=await tmdb(`/search/multi?language=pt-BR&include_adult=false&query=${encodeURIComponent(query)}`);results=data.results.filter(x=>x.media_type==='movie'||x.media_type==='tv');mode='search';render()}catch(error){message.textContent=error.message;if(!localStorage.getItem(KEY))$('#settings').showModal()}};
function openDetails(source){const stored=library.find(x=>uid(x)===uid(source)),item=stored||source;$('#detailsContent').innerHTML=`<div class="detail-hero">${poster(item)?`<img src="${poster(item)}" alt="">`:''}<div><p>${typeOf(item)==='tv'?'Série':'Filme'} · ${(item.release_date||item.first_air_date||'').slice(0,4)||'—'}</p><h2>${escapeHtml(titleOf(item))}</h2><p>${escapeHtml(item.overview||'Sinopse não disponível.')}</p></div></div><div class="detail-actions"><button data-status="watchlist">+ Quero assistir</button><button data-status="watching">▶ Assistindo</button><button data-status="watched">✓ Assistido</button><button data-favorite>${item.favorite?'★ Favorito':'☆ Favoritar'}</button>${stored?'<button data-remove>Remover da biblioteca</button>':''}</div>`;$('#detailsContent').querySelectorAll('[data-status]').forEach(button=>{if(item.status===button.dataset.status)button.classList.add('active');button.onclick=()=>upsert(item,{status:button.dataset.status})});$('#detailsContent').querySelector('[data-favorite]').onclick=()=>upsert(item,{favorite:!item.favorite});const remove=$('#detailsContent').querySelector('[data-remove]');if(remove)remove.onclick=()=>{library=library.filter(x=>uid(x)!==uid(item));save();$('#details').close();mode='library';render();toast('Removido')};$('#details').showModal()}
function upsert(item,change){const index=library.findIndex(x=>uid(x)===uid(item));const updated={...item,media_type:typeOf(item),...change};if(index<0)library.unshift(updated);else library[index]=updated;save();$('#details').close();mode='library';render();toast('Biblioteca atualizada')}
$('#filter').onchange=()=>{mode='library';render()};
document.querySelectorAll('dialog .close').forEach(button=>button.onclick=()=>button.closest('dialog').close());
$('#settingsButton').onclick=()=>{$('#tmdbKey').value=localStorage.getItem(KEY)||'';$('#settings').showModal()};
$('#saveKey').onclick=()=>{const key=$('#tmdbKey').value.trim();if(key)localStorage.setItem(KEY,key);else localStorage.removeItem(KEY);$('#settings').close();toast('Ajustes salvos')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),library},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`laysflix-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=async event=>{try{const data=JSON.parse(await event.target.files[0].text());if(!Array.isArray(data.library))throw 0;library=data.library;save();render();$('#settings').close();toast('Backup importado')}catch{toast('Arquivo de backup inválido')}};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderStats();render();
