const STORE='laysflix.library.v2',LEGACY='laysflix.library.v1',KEY='laysflix.tmdb.key';
const $=s=>document.querySelector(s), main=$('#main');
let library=loadLibrary(), view='home', homeData={trending:[],movies:[],series:[]};
function loadLibrary(){try{return JSON.parse(localStorage.getItem(STORE)||localStorage.getItem(LEGACY)||'[]')}catch{return[]}}
const save=()=>localStorage.setItem(STORE,JSON.stringify(library));
const typeOf=x=>x.media_type||(x.first_air_date?'tv':'movie'), uid=x=>`${typeOf(x)}:${x.id}`;
const titleOf=x=>x.title||x.name||'Sem título', yearOf=x=>(x.release_date||x.first_air_date||'').slice(0,4)||'—';
const poster=(x,size='w500')=>x?.poster_path?`https://image.tmdb.org/t/p/${size}${x.poster_path}`:'';
const backdrop=(x,size='original')=>x?.backdrop_path?`https://image.tmdb.org/t/p/${size}${x.backdrop_path}`:poster(x,'original');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const stored=x=>library.find(y=>uid(y)===uid(x));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2100)}
function tmdbAccess(){return localStorage.getItem(KEY)||window.LAYSFLIX_TMDB_TOKEN||window.LAYSFLIX_TMDB_API_KEY||''}
async function tmdb(path){const key=tmdbAccess();if(!key)throw new Error('Configure o acesso ao TMDB no perfil.');const bearer=key.startsWith('eyJ');const join=path.includes('?')?'&':'?';const response=await fetch(`https://api.themoviedb.org/3${path}${bearer?'':`${join}api_key=${encodeURIComponent(key)}`}`,{headers:{accept:'application/json',...(bearer?{Authorization:`Bearer ${key}`}:{})}});if(!response.ok)throw new Error(response.status===401?'Acesso ao TMDB inválido.':'Não foi possível carregar o catálogo.');return response.json()}
function card(x){const s=stored(x)||x, episodes=s.episodes||{},done=Object.values(episodes).filter(Boolean).length,total=s.episodeCount||0,pct=total?Math.min(100,done/total*100):s.status==='watched'?100:0;return `<article class="poster-card" data-open="${uid(x)}"><div class="poster-wrap">${poster(x)?`<img src="${poster(x)}" alt="Capa de ${esc(titleOf(x))}" loading="lazy">`:''}${s.favorite?'<button class="favorite" aria-label="Favorito">♥</button>':''}${pct?`<span class="progress"><i style="width:${pct}%"></i></span>`:''}</div><h3>${esc(titleOf(x))}</h3><p>${typeOf(x)==='tv'?'Série':'Filme'} · ${yearOf(x)}</p></article>`}
function rail(title,items,wide=false){if(!items?.length)return'';return `<section class="section"><div class="section-head"><h2>${title}</h2></div><div class="rail">${items.map(x=>wide?`<article class="wide-card" data-open="${uid(x)}"><img src="${backdrop(x,'w780')}" alt="" loading="lazy"><div><h3>${esc(titleOf(x))}</h3><p>★ ${Number(x.vote_average||0).toFixed(1)} · ${yearOf(x)}</p></div></article>`:card(x)).join('')}</div></section>`}
async function loadHome(){if(homeData.trending.length)return;try{const [t,m,s]=await Promise.all([tmdb('/trending/all/week?language=pt-BR'),tmdb('/movie/now_playing?language=pt-BR&region=BR'),tmdb('/tv/popular?language=pt-BR')]);homeData={trending:t.results.filter(x=>typeOf(x)!=='person'),movies:m.results,series:s.results};if(view==='home')renderHome()}catch(e){if(!localStorage.getItem(KEY))renderHome();else toast(e.message)}}
function renderHome(){const hero=homeData.trending[0]||library[0];main.innerHTML=`${hero?`<section class="home-hero"><div class="hero-image" style="background-image:url('${backdrop(hero)}')"></div><div class="hero-shade"></div><div class="hero-copy"><span class="eyebrow">Em destaque</span><h1>${esc(titleOf(hero))}</h1><p>${esc(hero.overview||'Sua próxima grande história começa aqui.')}</p><div class="hero-actions"><button class="primary" data-open="${uid(hero)}">▶ Ver detalhes</button><button class="secondary" data-add="${uid(hero)}">＋ Minha lista</button></div></div></section>`:`<section class="page-title"><p>Bem-vinda ao</p><h1>LaysFlix</h1><div class="empty"><b>Conecte seu catálogo</b>Abra o Perfil e informe o acesso ao TMDB para descobrir filmes e séries.</div></section>`}<div class="content">${rail('Continuar assistindo',library.filter(x=>x.status==='watching'))}${rail('Em alta esta semana',homeData.trending.slice(1,12),true)}${rail('Filmes no cinema',homeData.movies)}${rail('Séries populares',homeData.series)}${rail('Minha lista',library.filter(x=>x.status==='watchlist'))}</div>`;bindCards()}
function renderDiscover(){main.innerHTML=`<section class="page-title"><p>Explore o catálogo</p><h1>Descobrir</h1><form class="discover-search" id="discoverForm"><input type="search" placeholder="O que você quer assistir?"><button>Buscar</button></form></section><div class="content"><div class="chips"><button class="chip active">Para você</button><button class="chip">Filmes</button><button class="chip">Séries</button><button class="chip">Em alta</button></div>${rail('Tendências',homeData.trending,true)}${rail('Filmes para hoje',homeData.movies)}${rail('Séries para maratonar',homeData.series)}</div>`;$('#discoverForm').onsubmit=e=>{e.preventDefault();openSearch(e.currentTarget.querySelector('input').value)};bindCards()}
function renderLibrary(filter='all'){const items=library.filter(x=>filter==='all'||(filter==='favorite'?x.favorite:x.status===filter));main.innerHTML=`<section class="page-title"><p>${library.length} títulos salvos</p><h1>Biblioteca</h1></section><div class="content"><div class="chips" id="libraryFilters"><button class="chip ${filter==='all'?'active':''}" data-filter="all">Tudo</button><button class="chip ${filter==='watching'?'active':''}" data-filter="watching">Assistindo</button><button class="chip ${filter==='watchlist'?'active':''}" data-filter="watchlist">Quero ver</button><button class="chip ${filter==='watched'?'active':''}" data-filter="watched">Assistidos</button><button class="chip ${filter==='favorite'?'active':''}" data-filter="favorite">Favoritos</button></div>${items.length?`<div class="grid">${items.map(card).join('')}</div>`:'<div class="empty"><b>Nada por aqui ainda</b>Use Descobrir para adicionar filmes e séries.</div>'}</div>`;$('#libraryFilters').onclick=e=>{const f=e.target.dataset.filter;if(f)renderLibrary(f)};bindCards()}
function renderProfile(){const watching=library.filter(x=>x.status==='watching').length,watched=library.filter(x=>x.status==='watched').length,favs=library.filter(x=>x.favorite).length;main.innerHTML=`<section class="page-title"><p>Seu espaço</p><h1>Perfil</h1></section><div class="content"><section class="stats-card"><div class="stats-grid"><article><b>${library.length}</b><small>na biblioteca</small></article><article><b>${watched}</b><small>assistidos</small></article><article><b>${favs}</b><small>favoritos</small></article></div></section><section class="section"><div class="section-head"><h2>Sua jornada</h2></div><div class="profile-actions"><button data-library="watching"><span>▶ Assistindo agora</span><b>${watching} ›</b></button><button data-library="watchlist"><span>＋ Quero assistir</span><b>${library.filter(x=>x.status==='watchlist').length} ›</b></button><button id="profileSettings"><span>⚙ Ajustes e backup</span><b>›</b></button></div></section>${rail('Seus favoritos',library.filter(x=>x.favorite))}</div>`;$('#profileSettings').onclick=openSettings;main.querySelectorAll('[data-library]').forEach(b=>b.onclick=()=>switchView('library',b.dataset.library));bindCards()}
function switchView(next,filter){view=next;document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.view===next));scrollTo(0,0);({home:renderHome,discover:renderDiscover,library:()=>renderLibrary(filter),profile:renderProfile}[next])()}
function findItem(id){return [...library,...homeData.trending,...homeData.movies,...homeData.series].find(x=>uid(x)===id)}
function bindCards(){main.querySelectorAll('[data-open]').forEach(el=>el.onclick=e=>{if(e.target.closest('.favorite'))return;openDetail(findItem(el.dataset.open))});main.querySelectorAll('[data-add]').forEach(el=>el.onclick=()=>upsert(findItem(el.dataset.add),{status:'watchlist'}))}
async function openDetail(seed){if(!seed)return;const layer=$('#detailPage');layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#detailContent').innerHTML='<div class="detail-backdrop skeleton"></div><div class="detail-body"><div class="skeleton" style="height:180px;border-radius:20px"></div></div>';try{const type=typeOf(seed),[detail,credits,videos]=await Promise.all([tmdb(`/${type}/${seed.id}?language=pt-BR&append_to_response=watch/providers`),tmdb(`/${type}/${seed.id}/credits?language=pt-BR`),tmdb(`/${type}/${seed.id}/videos?language=pt-BR`)]);const item={...seed,...detail,media_type:type},s=stored(item)||item;renderDetail(item,s,credits.cast||[],videos.results||[])}catch(e){renderDetail(seed,stored(seed)||seed,[],[]);toast(e.message)}}
function renderDetail(item,s,cast,videos){const runtime=item.runtime||(item.episode_run_time||[])[0],genres=(item.genres||[]).slice(0,3);$('#detailContent').innerHTML=`<div class="detail-backdrop" style="background-image:url('${backdrop(item)}')"><button class="back" data-close-detail>‹</button></div><div class="detail-body"><div class="detail-meta"><span class="pill">${typeOf(item)==='tv'?'Série':'Filme'}</span><span class="pill">${yearOf(item)}</span>${runtime?`<span class="pill">${runtime} min</span>`:''}${item.vote_average?`<span class="pill">★ ${item.vote_average.toFixed(1)}</span>`:''}</div><h1>${esc(titleOf(item))}</h1><p>${genres.map(g=>g.name).join(' · ')}</p><p class="detail-overview">${esc(item.overview||'Sinopse não disponível.')}</p><div class="detail-actions"><button data-status="watchlist" class="${s.status==='watchlist'?'active':''}">＋ Quero ver</button><button data-status="watching" class="${s.status==='watching'?'active':''}">▶ Assistindo</button><button data-status="watched" class="${s.status==='watched'?'active':''}">✓ Assistido</button><button data-fav class="${s.favorite?'active':''}">${s.favorite?'♥ Favorito':'♡ Favoritar'}</button></div>${cast.length?`<section class="section"><div class="section-head"><h2>Elenco</h2></div><div class="people">${cast.slice(0,12).map(p=>`<div class="person">${p.profile_path?`<img src="https://image.tmdb.org/t/p/w185${p.profile_path}" alt="">`:'<div style="height:64px"></div>'}<span>${esc(p.name)}</span></div>`).join('')}</div></section>`:''}${typeOf(item)==='tv'&&item.seasons?.length?`<section class="section"><div class="section-head"><h2>Episódios</h2></div><select class="season-select" id="seasonSelect">${item.seasons.filter(x=>x.season_number>0).map(x=>`<option value="${x.season_number}">${esc(x.name)}</option>`).join('')}</select><div id="episodes"><p class="hint">Carregando episódios…</p></div></section>`:''}${videos.find(v=>v.site==='YouTube'&&v.type==='Trailer')?`<a class="primary" style="display:block;text-align:center;text-decoration:none" target="_blank" rel="noopener" href="https://youtube.com/watch?v=${videos.find(v=>v.site==='YouTube'&&v.type==='Trailer').key}">▶ Assistir trailer</a>`:''}</div>`;$('#detailContent [data-close-detail]').onclick=closeDetail;$('#detailContent').querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{upsert(item,{status:b.dataset.status});renderDetail(item,stored(item),cast,videos)});$('#detailContent [data-fav]').onclick=()=>{upsert(item,{favorite:!s.favorite});renderDetail(item,stored(item),cast,videos)};if($('#seasonSelect')){$('#seasonSelect').onchange=e=>loadEpisodes(item,+e.target.value);loadEpisodes(item,+$('#seasonSelect').value)}}
async function loadEpisodes(show,season){const box=$('#episodes');try{const data=await tmdb(`/tv/${show.id}/season/${season}?language=pt-BR`),s=stored(show)||show;box.innerHTML=data.episodes.map(ep=>{const key=`${season}:${ep.episode_number}`,done=s.episodes?.[key];return `<article class="episode"><button class="episode-check ${done?'done':''}" data-episode="${key}">${done?'✓':''}</button><div><h4>${ep.episode_number}. ${esc(ep.name)}</h4><p>${ep.runtime?`${ep.runtime} min · `:''}${ep.air_date||'Data indisponível'}</p></div></article>`}).join('');box.querySelectorAll('[data-episode]').forEach(b=>b.onclick=()=>{const current=stored(show)||show,episodes={...(current.episodes||{})};episodes[b.dataset.episode]=!episodes[b.dataset.episode];upsert(show,{status:'watching',episodes,episodeCount:show.number_of_episodes});loadEpisodes(show,season)})}catch(e){box.innerHTML=`<p class="hint">${esc(e.message)}</p>`}}
function closeDetail(){const layer=$('#detailPage');layer.classList.remove('open');layer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function upsert(item,change){const index=library.findIndex(x=>uid(x)===uid(item)),next={...item,media_type:typeOf(item),...change};if(index<0)library.unshift(next);else library[index]=next;save();toast('Biblioteca atualizada')}
function openSearch(initial=''){const layer=$('#searchPage');layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#searchInput').value=initial;$('#searchInput').focus();if(initial)search(initial)}
async function search(q){const box=$('#searchResults');box.innerHTML='<p class="hint">Buscando…</p>';try{const data=await tmdb(`/search/multi?language=pt-BR&include_adult=false&query=${encodeURIComponent(q)}`),items=data.results.filter(x=>['movie','tv'].includes(x.media_type));box.innerHTML=items.length?items.map(x=>`<article class="search-row" data-search-open="${uid(x)}">${poster(x)?`<img src="${poster(x,'w185')}" alt="">`:'<div class="search-placeholder"></div>'}<div><h3>${esc(titleOf(x))}</h3><p>${typeOf(x)==='tv'?'Série':'Filme'} · ${yearOf(x)}</p><p>${esc((x.overview||'').slice(0,120))}</p></div></article>`).join(''):'<div class="empty"><b>Nenhum resultado</b>Tente buscar com outro nome.</div>';box.querySelectorAll('[data-search-open]').forEach(el=>el.onclick=()=>{const item=items.find(x=>uid(x)===el.dataset.searchOpen);closeSearch();openDetail(item)})}catch(e){box.innerHTML=`<div class="empty"><b>Não foi possível buscar</b>${esc(e.message)}</div>`}}
function closeSearch(){$('#searchPage').classList.remove('open');$('#searchPage').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openSettings(){$('#tmdbKey').value=localStorage.getItem(KEY)||'';$('#tmdbKey').placeholder=window.LAYSFLIX_TMDB_TOKEN?'Acesso automático ativo':'Cole aqui';$('#settings').showModal()}
document.querySelectorAll('.tabbar button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$('#brandButton').onclick=()=>switchView('home');$('#searchButton').onclick=()=>openSearch();$('#settingsButton').onclick=()=>switchView('profile');
$('#searchForm').onsubmit=e=>{e.preventDefault();const q=$('#searchInput').value.trim();if(q)search(q)};$('[data-close-search]').onclick=closeSearch;
$('#settings .close').onclick=()=>$('#settings').close();$('#saveKey').onclick=()=>{const key=$('#tmdbKey').value.trim();key?localStorage.setItem(KEY,key):localStorage.removeItem(KEY);$('#settings').close();homeData={trending:[],movies:[],series:[]};loadHome();toast('Acesso salvo neste aparelho')};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),library},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`laysflix-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('#importData').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(!Array.isArray(data.library))throw 0;library=data.library;save();$('#settings').close();switchView('library');toast('Backup importado')}catch{toast('Backup inválido')}};
addEventListener('popstate',()=>{if($('#detailPage').classList.contains('open'))closeDetail();else if($('#searchPage').classList.contains('open'))closeSearch()});
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=4'));
renderHome();loadHome();
